version: '3.8'
services:
  artesaniasfrontend:
    image: brayan22/artesanias-frontend:latest
    networks:
      - reverse-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse-proxy"
        - "traefik.http.routers.artesaniasfrontend.entrypoints=web"
        - "traefik.http.routers.artesaniasfrontend.rule=Host(`artesaniasbogota.${DOMAIN}`)"
        - "traefik.http.routers.artesaniasfrontend.service=artesaniasfrontend"
        - "traefik.http.services.artesaniasfrontend.loadbalancer.server.port=80"
        #- "traefik.http.routers.artesaniasfrontend.tls=true"
        #- "traefik.http.routers.artesaniasfrontend.tls.certresolver=cloudflare"
        #- "traefik.http.routers.artesaniasfrontend.tls.domains[0].main=${DOMAIN}"
        #- "traefik.http.routers.artesaniasfrontend.tls.domains[0].sans=*.${DOMAIN}"
networks:
  reverse-proxy:
    external: true
