version: '3.8'
services:
  react-app:
    image: brayan22/artesanias-frontend:latest
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - reverse-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse-proxy"
        - "traefik.http.routers.jenkins.entrypoints=websecure"
        - "traefik.http.routers.jenkins.rule=Host(`artesaniasbogota.${DOMAIN}`)"
        - "traefik.http.routers.jenkins.service=jenkins"
        - "traefik.http.services.jenkins.loadbalancer.server.port=3000"
        - "traefik.http.routers.jenkins.tls=true"
        - "traefik.http.routers.jenkins.tls.certresolver=cloudflare"
        - "traefik.http.routers.jenkins.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.jenkins.tls.domains[0].sans=*.${DOMAIN}"
networks:
  reverse-proxy:
    external: true